 const triproutes = [
    {
        route_num:1,
        order_number: "Dp25091",
        sales_person: "Maria",
        sales_person_contact:"",
        cust_addr_1:"",
        cust_addr_2:"",
        cust_city:"",
        cust_state:"",
        cust_zip:"",
        cust_phone: "314-254-6325",
        cust_mobile: "314-957-8547",
        service_details: "drop",
        inclines: "elevator",
        order_notes: "The customer would like to get a call an hour before we arrive",
        route_ready_status:"",
        checklist: false,
        pre_trip_contact: false,
        enroute: false,
        delivered:false,
        working:false,
        completed:false
      },
      {
        route_num:2,
        order_number: "Dp25091",
        sales_person: "Maria",
        sales_person_contact:"",
        cust_addr_1:"",
        cust_addr_2:"",
        cust_city:"",
        cust_state:"",
        cust_zip:"",
        cust_phone: "314-254-6325",
        cust_mobile: "314-957-8547",
        service_details: "drop",
        inclines: "elevator",
        order_notes: "The customer would like to get a call an hour before we arrive",
        route_ready_status:"",
        checklist: false,
        pre_trip_contact: false,
        enroute: false,
        delivered:false,
        working:false,
        completed:false
      },
      {
        route_num:3,
        order_number: "Dp25091",
        sales_person: "Maria",
        sales_person_contact:"",
        cust_addr_1:"",
        cust_addr_2:"",
        cust_city:"",
        cust_state:"",
        cust_zip:"",
        cust_phone: "314-254-6325",
        cust_mobile: "314-957-8547",
        service_details: "drop",
        inclines: "elevator",
        order_notes: "The customer would like to get a call an hour before we arrive",
        route_ready_status:"",
        checklist: false,
        pre_trip_contact: false,
        enroute: false,
        delivered:false,
        working:false,
        completed:false
      },
]

export default triproutes